name: merge main into production

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge main into production
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}
